# Uncomment the next line to define a global platform for your project
# platform :ios, ‘9.0’
use_frameworks!

target 'HotNewsSwift' do
 
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'SVProgressHUD'
    pod 'YYModel'

end
